### ISSUE TITLE
AVISO IMPORTANTE

### ISSUE THREAD

**Issue by pedropolisenso** [front-end-carioca/fec-2014#17]
@andrevvalle @jotaefe @luisfernandomangia todas as tarefas referente ao projeto do site como melhorias, ajustes, alinhamentos, inserção de conteúdos, precisam ser inseridos aqui através das issue, para que todos saibam o que está rolando de novo no site, ok?

É super importante criar a issue primeiro e depois realizar a tarefa, assim que realizar a tarefa, feche a issue informando que ja foi resolvido.

OBS: Por padronização, e isso server até para mim, vamos tentar manter os commits legíveis e em inglês.

PS: Peço que quando lerem este aviso confirmem com um OK. Abraços!

**Comment by andrevvalle** [comment]
ta ok!! @pedropolisenso

**Comment by fredericksilva** [comment]
Ok !
